spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

telegrambots:
  enabled: true
  bots:
    - name: weathernotifications
      username: weathernotificationperdaybot
      token: 8196905883:AAHcQp2Bm17oMPXviz1QZnHmbyqszAnQ9WU